### ISSUE TITLE
Is "ensuring" correct?

### ISSUE THREAD

**Issue by npdoty** [w3c/beacon#21]
The introduction notes that Beacon will "ensure" that data is delivered to the destination. Is this what's intended? It seems to provide a higher level of guarantee than I expected, especially given that Beacon is explicitly noted as being de-prioritized in some cases for performance reasons. And for privacy reasons, I expect there may be some situations where the spec will state that a request shouldn't be delivered or where a user will choose not to deliver. Reliable delivery is important to encourage sites to use sendBeacon as opposed to painful onunload measures, but I thought we were noting this as best effort rather than a sure thing.

(Apologies for opening an issue on a small point, but I think it's important.)

**Comment by igrigorik** [comment]
> The user agent is allowed to restrict the maximum accepted payload size to ensure that beacon requests are able to complete quickly and in a timely manner.

I'm assuming that's the part we're talking about? We should probably reword that.. Forcing a small payload size does not "ensure" fast delivery, but it does rule out a class of pathological cases where a large payload can take a long time to transfer. I just wanted to highlight that we intentionally rule this out.

The other two mentions of "ensure" in the introduction are with respect to developers holding the user agent from continuing its processing, to "ensure" that their requests are not cancelled. I think that language is fine?

> It seems to provide a higher level of guarantee than I expected, especially given that Beacon is explicitly noted as being de-prioritized in some cases for performance reasons. 

Beacon is not de-prioritized. We do say beacon requests may be delayed + coalesced to improve performance, but this does not mean we treat it as a "lesser" fetch.

> And for privacy reasons, I expect there may be some situations where the spec will state that a request shouldn't be delivered or where a user will choose not to deliver.

That's not the case today and I don't think this makes sense, unless you're disabling JS outright and simultaneously disable XHR + fetch. 

> Reliable delivery is important to encourage sites to use sendBeacon as opposed to painful onunload measures, but I thought we were noting this as best effort rather than a sure thing.

All requests are best-effort, including sendBeacon. I don't think we claim otherwise in the current draft?

**Comment by igrigorik** [comment]
@npdoty happy 2016! And, _nudge.._ Can we resolve this one? :)

**Comment by toddreifsteck** [comment]
@npdoty Any pushback on us resolving this? If we don't hear back in 2 weeks, we'll resolve this issue.

**Comment by npdoty** [comment]
@igrigorik @toddreifsteck apologies for the delay, will review and respond to these this week. (After the first round-trip on this feedback took a year between TPAC meetings, I was unprepared! I should respond more promptly.)

**Comment by npdoty** [comment]
I had missed the change and corresponding bullet point about Beacons always being executed on state change, as opposed to some potential future date. Given that, I think I understand "ensure" now as a regular best-effort delivery, with the advantage of being non-blocking on other tasks.

For what it's worth, I think it is quite clear in the text that Beacons may be de-prioritized, for example, not happening immediately when the UA chooses to batch them up to save battery. But I don't think that affects the level of ensuring delivery, beyond some narrow edge case.

Closing because I think my concern is addressed. @igrigorik if you wanted to re-word that section about size and ensuring fast delivery, you can re-open this issue or just make the change directly, but I don't think it's essential.
